checkpoint_period: 1000000000
main_cpu_set: [4]
checker_cpu_set: [0, 1, 2, 3]
max_nr_live_segments: 5
exec_point_replay: true
slicer: !FixedInterval
dump_stats: !StdOut
hwmon_sensor_paths:
- hwmon: macsmc_hwmon
  sensor: CPU P-cores Power
- hwmon: macsmc_hwmon
  sensor: CPU E-cores Power
- hwmon: macsmc_hwmon
  sensor: SoC Power
- hwmon: macsmc_hwmon
  sensor: DRAM VDD2H Power
- hwmon: macsmc_hwmon
  sensor: CPU SRAM 1 Power
- hwmon: macsmc_hwmon
  sensor: CPU SRAM 2 Power
