[package]
name = "reldrv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch."https://github.com/rust-lang/libc"]
libc = { git = "https://github.com/mbyzhang/libc.git", branch = "ptrace-o-allow-tracer-thread-group" }

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
nix = { git = "https://github.com/mbyzhang/nix.git", branch = "ptrace-get-rseq-configuration" }
compel = { git = "https://github.com/mbyzhang/compel-rs.git", optional = true }
parasite = { path = "parasite", optional = true }
procfs = { git = "https://github.com/mbyzhang/procfs.git" }
pretty-hex = "0.3.0"
parking_lot = "0.12.1"
bitflags = "1.3.2"
reverie-syscalls = { path = "../reverie-syscalls" }
syscalls = "*"
log-panics = { version = "2", features = ["with-backtrace"]}

[build-dependencies]
cc = "1.0.78"

[dev-dependencies]
serial_test = "2.0.0"
tempfile = "3"

[profile.release]
debug = true

[features]
default = []
compel = ["dep:compel", "dep:parasite"]
