[package]
name = "reldrv"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
log = "0.4.17"
nix = { git = "https://github.com/mbyzhang/nix.git", branch = "ptrace-get-rseq-configuration" }
procfs = { git = "https://github.com/mbyzhang/procfs.git" }
pretty-hex = "0.3.0"
bitflags = "1.3.2"
reverie-syscalls = { path = "../reverie-syscalls" }
syscalls = "*"
log-panics = { version = "2", features = ["with-backtrace"]}
lazy-init = "*"
perf-event2 = "0.7.2"
thiserror = "1.0.43"
human_bytes = "0.4.2"
lazy_static = "1.4.0"
libfpt-rs = { path = "../libfpt-rs" }
clap-num = "1.0.2"
unwind = { version = "0.4.1", features = ["ptrace"] }
parking_lot = "0.12.1"
downcast-rs = "1.2.0"
typed-arena = "2.0.2"
pretty_env_logger = "0.5.0"

[build-dependencies]
cc = "1.0.78"

[dev-dependencies]
serial_test = "2.0.0"
tempfile = "3"

[profile.release]
debug = true

[features]
default = ["intel_cat"]
intel_cat = []
